SecDebugLogLevel 9
SecDebugLog /dev/stdout

SecRequestBodyAccess On

# Set limits
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072

SecResponseBodyAccess On
SecResponseBodyLimit 10485760
SecResponseBodyMimeType text/plain text/html text/xml application/json application/hal+json application/problem+json

Include /rules/rules/*.conf